# Generated by Django 4.1.6 on 2023-03-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.CharField(default='', max_length=50)),
                ('stream_id', models.CharField(default='', max_length=10)),
                ('title', models.CharField(default='', max_length=50)),
                ('text', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
