# Generated by Django 4.1.6 on 2023-03-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='stream_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
